# Experiment A-3

In [3]:
import numpy as np

def ascii_bits(ch):
    return [int(bit) for bit in format(ord(ch), '08b')]

digits = [str(i) for i in range(10)]

X = np.array([ascii_bits(d) for d in digits])

print("AscII values \n",X)
Y = np.array([int(d) % 2 for d in digits])

w = np.zeros(8)
b = 0
lr = 0.1

for epoch in range(100):

    error = 0

    for x, y in zip(X, Y):

        net = np.dot(w, x) + b

        pred = 1 if net >= 0 else 0

        update = lr * (y - pred)

        w = w + update * x
        b = b + update

        error += abs(update)

    if error == 0:
        print("Training completed in", epoch + 1, "epochs")
        break

print("\nDigit  Prediction")
print("------------------")

correct = 0

for d, x, y in zip(digits, X, Y):

    net = np.dot(w, x) + b
    pred = 1 if net >= 0 else 0

    result = "Odd" if pred == 1 else "Even"

    print(d, "   ->   ",ord(d),"   ->   ", result)

    if pred == y:
        correct += 1

accuracy = (correct / len(digits)) * 100

# print("\nAccuracy =", accuracy, "%")

AscII values 
 [[0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 1]
 [0 0 1 1 0 0 1 0]
 [0 0 1 1 0 0 1 1]
 [0 0 1 1 0 1 0 0]
 [0 0 1 1 0 1 0 1]
 [0 0 1 1 0 1 1 0]
 [0 0 1 1 0 1 1 1]
 [0 0 1 1 1 0 0 0]
 [0 0 1 1 1 0 0 1]]
Training completed in 3 epochs

Digit  Prediction
------------------
0    ->    48    ->    Even
1    ->    49    ->    Odd
2    ->    50    ->    Even
3    ->    51    ->    Odd
4    ->    52    ->    Even
5    ->    53    ->    Odd
6    ->    54    ->    Even
7    ->    55    ->    Odd
8    ->    56    ->    Even
9    ->    57    ->    Odd
