In [12]:
import numpy as np
def ascii(ch) :
    return [int(bit) for bit in format(ord(ch),'08b')]

digit = [str(i) for i in range(10)]

X = np.array([ascii(d) for d in digit])
Y = np.array([int(d) % 2 for d in digit])

print(X)
print(digit)
print(Y)

w = np.zeros(8)
lr = 0.1 
b = 0


[[0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 1]
 [0 0 1 1 0 0 1 0]
 [0 0 1 1 0 0 1 1]
 [0 0 1 1 0 1 0 0]
 [0 0 1 1 0 1 0 1]
 [0 0 1 1 0 1 1 0]
 [0 0 1 1 0 1 1 1]
 [0 0 1 1 1 0 0 0]
 [0 0 1 1 1 0 0 1]]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
[0 1 0 1 0 1 0 1 0 1]


In [15]:
for epoch in range(100) : 
    error = 0
    for x,y in zip(X,Y) :
        net = np.dot(w,x) + b 
        pred = 1 if net >= 0 else 0 

        update = (y - pred) * lr
        w += update *x 
        b += update 
        error += abs(update)
    if(error == 0) : 
        print("Traing complete.",epoch+1,"epoch")

Traing complete. 1 epoch
Traing complete. 2 epoch
Traing complete. 3 epoch
Traing complete. 4 epoch
Traing complete. 5 epoch
Traing complete. 6 epoch
Traing complete. 7 epoch
Traing complete. 8 epoch
Traing complete. 9 epoch
Traing complete. 10 epoch
Traing complete. 11 epoch
Traing complete. 12 epoch
Traing complete. 13 epoch
Traing complete. 14 epoch
Traing complete. 15 epoch
Traing complete. 16 epoch
Traing complete. 17 epoch
Traing complete. 18 epoch
Traing complete. 19 epoch
Traing complete. 20 epoch
Traing complete. 21 epoch
Traing complete. 22 epoch
Traing complete. 23 epoch
Traing complete. 24 epoch
Traing complete. 25 epoch
Traing complete. 26 epoch
Traing complete. 27 epoch
Traing complete. 28 epoch
Traing complete. 29 epoch
Traing complete. 30 epoch
Traing complete. 31 epoch
Traing complete. 32 epoch
Traing complete. 33 epoch
Traing complete. 34 epoch
Traing complete. 35 epoch
Traing complete. 36 epoch
Traing complete. 37 epoch
Traing complete. 38 epoch
Traing complete. 39 e

In [19]:
correct = 0
for d,x,y in zip(digit,X,Y) : 
    net = np.dot(w,x) + b 
    pred = 1 if net >= 0 else 0 
    
    res = "odd" if pred == 1 else "even" 

    print(d," ->",ord(d)," ->", res) 

    if(pred == y) : 
        correct += 1 

acc = correct / len(digit) 
print(int(acc*100))

0  -> 48  -> even
1  -> 49  -> odd
2  -> 50  -> even
3  -> 51  -> odd
4  -> 52  -> even
5  -> 53  -> odd
6  -> 54  -> even
7  -> 55  -> odd
8  -> 56  -> even
9  -> 57  -> odd
100
